### ISSUE TITLE
Runs every second

### ISSUE THREAD

**Issue by wmertens** [kentcdodds/react-detector#3]
I see that it checks again every second, querying the full DOM every time. This makes all tabs that don't use React use CPU, even if it is a little. That in turn uses battery for no reason.

Could you stop checking after a minute?

**Comment by kentcdodds** [comment]
This checking was implemented by @spicyj and merged by me because of #1 and I really don't see this being a big issue battery/CPU-wise. I don't have any benchmark or anything to back me up though...

I suppose we could make this configurable, but I think most people don't really care. You're welcome to make a PR to support some kind of configuration feature.

**Comment by kentcdodds** [comment]
Going to go ahead and close this. I'm not convinced this is a real issue.
